# These are supported funding model platforms

github: [saitejabandaru-in]
open_collective: vite-plugin-asset-pack
ko_fi: saitejabandaru-in
custom: ['https://github.com/saitejabandaru-in/vite-plugin-asset-pack/blob/main/SPONSORS.md']
